### ISSUE TITLE
memory lead detected

### ISSUE THREAD

**Issue by arthurtalkgoal** [MCluck90/simple-ssh#20]
I got the member leak detected error in my production server log when running a ssh codes calling bash sh.

```
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Connection.addListener (events.js:179:15)
    at Connection.once (events.js:204:8)
    at new ChannelStream (/myfolder/shared/node_modules/simple-ssh/node_modules/ssh2/lib/Channel.js:578:17)
    at /myfolder/shared/node_modules/simple-ssh/node_modules/ssh2/lib/Channel.js:360:20
    at Parser.<anonymous> (/myfolder/shared/node_modules/simple-ssh/node_modules/ssh2/lib/Channel.js:142:30)
    at Parser.emit (events.js:104:17)
    at Parser.parsePacket (/myfolder/shared/node_modules/simple-ssh/node_modules/ssh2/lib/Parser.js:632:12)
    at Parser.execute (/myfolder/shared/node_modules/simple-ssh/node_modules/ssh2/lib/Parser.js:249:14)
    at Socket.<anonymous> (/myfolder/shared/node_modules/simple-ssh/node_modules/ssh2/lib/Connection.js:536:18)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)
    at TCP.onread (net.js:529:20)


```

**Comment by MCluck90** [comment]
Hmmm... This only shows what was happening inside of the ssh2 module at the time. Is there any way you could determine what exactly you were doing with simple-ssh at the time?

**Comment by arthurtalkgoal** [comment]
Hi Mike,  i am still debugging it.  It is likely relate to production storage issue, but Weird that my node app works but not pm2 start.    Let me confirm it when I can run the production

Arthur CHAN

Co-founder
Talkgoal.com

**Comment by arthurtalkgoal** [comment]
Hi @MCluck90 ,

I think I can put my bet one this problem, I found same problem , It said similar problem like below over time

```

(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emi
tter.setMaxListeners() to increase limit.
Trace
    at Connection.addListener (events.js:179:15)
    at SSH.on (/home/deploy/hub/shared/node_modules/simple-ssh/lib/ssh.js:264:13)
    at that.updateClientEnv (/myapp/lib/utils/device.js:65:

```

where line 65 ```devise.js``` is my ***on("errror") function:

```
ssh.on('error', function(err)

```

Is it a memory leak problem if I call more  ***ssh.on("error")*** than  ***ssh.start()*** ?

It happens since my promise return the ssh object itself without call return the start().

**Comment by MCluck90** [comment]
It's not an error to call `ssh.on('error', cb)` more often than `ssh.start()` but it sounds like you are adding more listeners to `ssh.on('error')` over time without removing old ones. If this is on purpose, you don't have a problem but it might end up using all of your memory over a long period of time. Otherwise, make sure you're using `ssh.off('error', cb)` to remove event listeners you don't need anymore.

Put another way, say I was doing something like this:

```javascript
var ssh = new SSH();
setTimeout(function loop() {
  // Do something
  ssh.on('error', function() { ... });
  setTimeout(loop, 30000);
}, 30000);
```

then every 30 seconds I'm adding a new listener without removing it. This can be fixed like this:

```javascript
var ssh = new SSH();
function onError() { ... }
setTimeout(function loop() {
  // Remove the error handler
  ssh.off('error', onError);

  // Do something
  ssh.on('error', onError);
  setTimeout(loop, 30000);
}, 30000);
```

A setup similar to this ensures that you aren't just adding more and more error handlers.

Does this help?

**Comment by arthurtalkgoal** [comment]
Hi @MCluck90 

Thanks so much!   You gave me the best guidelines!
