### ISSUE TITLE
 Does not work on Mac OS.

### ISSUE THREAD

**Issue by binshuuuu** [MCluck90/simple-ssh#61]
Your source is very convenient and powerful.

However, when I try to connect to SSH on Mac OS, I get a problem.

On Linux ssh userName @ IP.
Command to ssh on MacOS, but is there any way to fix this on Windows?

**Comment by MCluck90** [comment]
Hi! Sorry to hear you're having a problem. However, without a more descriptive error message, I'm afraid I can't help. Mac OS is a Unix based system so if you can connect to a Linux box, you can almost definitely connect to a Mac. I can also say I've personally used this on a Windows machine to connect to a Mac machine. Feel free to open this issue if you can provide a more descriptive error message.

**Comment by binshuuuu** [comment]
It was a quick answer, thank you.
But the problem has not been solved yet.

`var IP = result[0].SV_PC_IP;
	var NAME = result[0].SV_PC_NAME;
	var PW = result[0].SV_PC_PW;
	
	var sshLinux = new SSH({
	    host: IP,
	    user: NAME,
	    pass: PW,
	    passphrase : PW
	});
	

	sshLinux.exec('sudo shutdown -h now', {
	    err: function(stderr) {
	        console.log(stderr); // this-does-not-exist: command not found
	    },
	    out: function(stdout) {
	        console.log(IP + " - Echo : " , stdout);
	    }
	    
	}).start();
	
	sshLinux.on('error', function(err) {
	    console.log('[ SSH ]  ERROR ');
	    console.log(err);
	    sshLinux.end();
	});`

This is the code I used for ssh.
And it generates this error message.
I do not know why I am doing this.
Do you know how to fix this?


{ Error: All configured authentication methods failed
    at tryNextAuth (E:\workspace\dnsm_system\node_modules\ssh2\lib\client.js:380:17)
    at SSH2Stream.onUSERAUTH_FAILURE (E:\workspace\dnsm_system\node_modules\ssh2\lib\client.js:591:5)
    at emitTwo (events.js:106:13)
    at SSH2Stream.emit (events.js:191:7)
    at parsePacket (E:\workspace\dnsm_system\node_modules\ssh2-streams\lib\ssh.js:3929:10)
    at SSH2Stream._transform (E:\workspace\dnsm_system\node_modules\ssh2-streams\lib\ssh.js:669:13)
    at SSH2Stream.Transform._read (_stream_transform.js:167:10)
    at SSH2Stream._read (E:\workspace\dnsm_system\node_modules\ssh2-streams\lib\ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:155:12)
    at doWrite (_stream_writable.js:331:12) level: 'client-authentication' }

**Comment by MCluck90** [comment]
It appears that your authentication information is incorrect. It's
connecting to the machine but failing to authenticate. Check your username,
password, and IP address.
